fix: clarify the file name to be used (#1170)
As I was following the steps in this page -
https://docs.npmjs.com/creating-node-js-modules, I noticed the following
error when using the published package in the test-directory:

`Error: Cannot find module
'D:\Learning\npm-docs\use-hello\node_modules\@andrewnessindev\hello\index.js'.
Please verify that the package.json has a valid "main" entry`

It turned out that I missed providing the main entry even though this
[page already mentions to provide
it](https://github.com/npm/documentation/blob/2e10e4ed46f0f58adf4c165e8ef21599bc3b325f/content/packages-and-modules/contributing-packages-to-the-registry/creating-node-js-modules.mdx?plain=1#L20).
However, it might be more helpful if the docs clarify which file is
referred to when[ it says, "In the
file"](https://github.com/npm/documentation/blob/2e10e4ed46f0f58adf4c165e8ef21599bc3b325f/content/packages-and-modules/contributing-packages-to-the-registry/creating-node-js-modules.mdx?plain=1#L28).

This is my first commit! I followed the instruction it the
`contributing.md` file for the commit message. I did not see a
requirement to raise an issue first! Please do let me know if I have to
raise an issue first or if I have missed anything else.

---------

Co-authored-by: Gar <wraithgar@github.com>